-- Create PERSON table

CREATE TABLE PERSON (
    USERNAME CHAR(32) NOT NULL PRIMARY KEY,
    EMAIL CHAR(64) NOT NULL UNIQUE,
    PASSWORD CHAR(64) NOT NULL,
    FIRST_NAME CHAR(32),
    LAST_NAME CHAR(32),
    GENDER INT,
    BIRTHDAY DATE,
    PIC BLOB
);

CREATE TABLE PERSONPHONE (
    PERSON_USERNAME CHAR(32),
    PHONE CHAR(13),
    CONSTRAINT PERSON_PHONE_PRIMARY_KEY PRIMARY KEY (PERSON_USERNAME, PHONE)
);

ALTER TABLE PERSONPHONE ADD FOREIGN KEY (PERSON_USERNAME) REFERENCES PERSON(USERNAME) ON UPDATE CASCADE;

CREATE TABLE PERSONADDRESS (
    PERSON_USERNAME CHAR(32) REFERENCES PERSON(USERNAME) ON UPDATE CASCADE,
    ADDRESS CHAR(64),
    CONSTRAINT PERSON_ADDRESS_PRIMARY_KEY PRIMARY KEY (PERSON_USERNAME, ADDRESS)
);