CREATE TABLE WHO_EDITED_PRODUCT (
    USERNAME CHAR(32) REFERENCES ADMIN(USERNAME) ON UPDATE CASCADE,
    PID INT REFERENCES PRODUCT(PID) ON UPDATE CASCADE,
    MOD_DATE TIMESTAMP,
    CONSTRAINT PK_HOW_EDITED_PRODUCT PRIMARY KEY (USERNAME, PID, MOD_DATE)
);

CREATE TABLE CART (
    USERNAME CHAR(32) REFERENCES MYUSER(USERNAME) ON UPDATE CASCADE,
    PID INT REFERENCES PRODUCT(PID) ON UPDATE CASCADE,
    DATE_ADDED TIMESTAMP,
    QUANTITY INT,
    CONSTRAINT PK_CART PRIMARY KEY (USERNAME, PID, DATE_ADDED)
);

CREATE TABLE FAVORITE (
    USERNAME CHAR(32) REFERENCES MYUSER(USERNAME) ON UPDATE CASCADE,
    PID INT REFERENCES PRODUCT(PID) ON UPDATE CASCADE,
    DATE_ADDED TIMESTAMP,
    CONSTRAINT PK_FAVORITE PRIMARY KEY (USERNAME, PID, DATE_ADDED)
);

CREATE TABLE SALES (
    USERNAME CHAR(32) REFERENCES MYUSER(USERNAME) ON UPDATE CASCADE,
    PID INT REFERENCES PRODUCT(PID) ON UPDATE CASCADE,
    DATE_ADDED TIMESTAMP,
    QUANTITY INT,
    CONSTRAINT PK_SALES PRIMARY KEY (USERNAME, PID, DATE_ADDED)
);