DROP TABLE IF EXISTS `ADMIN`;

DROP TABLE IF EXISTS `CART`;

DROP TABLE IF EXISTS `WHO_EDITED_PRODUCT`;

DROP TABLE IF EXISTS `VISA_MYUSER`;

DROP TABLE IF EXISTS `SALES`;

DROP TABLE IF EXISTS `PRODUCT`;

DROP TABLE IF EXISTS `PERSONADDRESS`;

DROP TABLE IF EXISTS `PERSONPHONE`;

DROP TABLE IF EXISTS `MYUSER`;

DROP TABLE IF EXISTS `PERSON`;

DROP TABLE IF EXISTS `FAVORITE`;