CREATE SEQUENCE PRODUCT_ID_SEQ;

CREATE TABLE PRODUCT (
    PID INT NOT NULL PRIMARY KEY,
    NAME CHAR(64),
    DESCRIPTION VARCHAR2(2048),
    RATING BINARY_DOUBLE,
    STOCK INT,
    PICTURE BLOB,
    PRICE FLOAT(20),
    CATEGORY CHAR(32),
    DISCOUNT INT
);

CREATE TRIGGER PRODUCT_BI BEFORE
    INSERT ON PRODUCT FOR EACH ROW
BEGIN
    SELECT
        PRODUCT_ID_SEQ.NEXTVAL INTO :NEW.PID
    FROM
        PRODUCT;
END;