-- Create a USER table

CREATE TABLE MYUSER (
    USERNAME CHAR(32) NOT NULL PRIMARY KEY REFERENCES PERSON(USERNAME)
);

CREATE TABLE VISA_MYUSER (
    PERSON_USERNAME CHAR(32) REFERENCES MYUSER(USERNAME),
    HOLDER_NAME CHAR(32),
    VISA_NUMBER CHAR(16),
    CVV CHAR(3),
    EXPIRATION_DATE CHAR(5),
    CONSTRAINT PK_PERSON_VISA PRIMARY KEY (PERSON_USERNAME, VISA_NUMBER)
);